--- configuration/config.toml.orig	2014-11-07 13:36:50.977788624 +0100
+++ configuration/config.toml	2014-11-07 13:46:50.727794155 +0100
@@ -5,20 +5,31 @@
 # that can be resolved here.
 # hostname = ""
 
+bind-address = "0.0.0.0"
+
+# Once every 24 hours InfluxDB will report anonymous data to m.influxdb.com
+# The data includes raft name (random 8 bytes), os, arch and version
+# We don't track ip addresses of servers reporting. This is only used
+# to track the number of instances running and the versions which
+# is very helpful for us.
+# Change this option to true to disable reporting.
+reporting-disabled = false
+
 [logging]
 # logging level can be one of "debug", "info", "warn" or "error"
 level  = "info"
-file   = "influxdb.log"
+file   = "/var/log/influxdb.log" # stdout to log to standard out, or syslog facility
 
 # Configure the admin server
 [admin]
 port   = 8083                   # binding is disabled if the port isn't set
-assets = "./admin"
+assets = "/usr/local/shared/influxdb/admin"
 
 # Configure the http api
 [api]
-ssl-port = 8087    # Ssl support is enabled if you set a port and cert
-ssl-cert = "../cert.pem"
+port     = 8086    # binding is disabled if the port isn't set
+# ssl-port = 8084    # Ssl support is enabled if you set a port and cert
+# ssl-cert = /path/to/cert.pem
 
 # connections will timeout after this amount of time. Ensures that clients that misbehave
 # and keep alive connections they don't use won't end up connection a million times.
@@ -30,13 +41,34 @@
   # Configure the graphite api
   [input_plugins.graphite]
   enabled = false
-  port = 2003
-  database = ""  # store graphite data in this database
+  # address = "0.0.0.0" # If not set, is actually set to bind-address.
+  # port = 2003
+  # database = ""  # store graphite data in this database
+  # udp_enabled = true # enable udp interface on the same port as the tcp interface
 
+  # Configure the collectd api
+  [input_plugins.collectd]
+  enabled = false
+  # address = "0.0.0.0" # If not set, is actually set to bind-address.
+  # port = 25826
+  # database = ""
+  # types.db can be found in a collectd installation or on github:
+  # https://github.com/collectd/collectd/blob/master/src/types.db
+  # typesdb = "/usr/share/collectd/types.db" # The path to the collectd types.db file
+
+  # Configure the udp api
   [input_plugins.udp]
-  enabled = true
-  port = 4444
-  database = "test"
+  enabled = false
+  # port = 4444
+  # database = ""
+
+  # Configure multiple udp apis each can write to separate db.  Just
+  # repeat the following section to enable multiple udp apis on
+  # different ports.
+  [[input_plugins.udp_servers]] # array of tables
+  enabled = false
+  # port = 5551
+  # database = "db1"
 
 # Raft configuration
 [raft]
@@ -46,20 +78,72 @@
 port = 8090
 
 # Where the raft logs are stored. The user running InfluxDB will need read/write access.
-dir  = "/tmp/influxdb/development/raft"
+dir  = "/var/db/influxdb/raft"
 
 # election-timeout = "2s"
 
 [storage]
-dir = "/tmp/influxdb/development/db"
+dir = "/var/db/influxdb/db"
 # How many requests to potentially buffer in memory. If the buffer gets filled then writes
 # will still be logged and once the local storage has caught up (or compacted) the writes
 # will be replayed from the WAL
 write-buffer-size = 10000
 
-# The server will check this often for shards that have expired and should be cleared.
+# the engine to use for new shards, old shards will continue to use the same engine
+default-engine = "rocksdb"
+
+# The default setting on this is 0, which means unlimited. Set this to something if you want to
+# limit the max number of open files. max-open-files is per shard so this * that will be max.
+max-open-shards = 0
+
+# The default setting is 100. This option tells how many points will be fetched from LevelDb before
+# they get flushed into backend.
+point-batch-size = 100
+
+# The number of points to batch in memory before writing them to leveldb. Lowering this number will
+# reduce the memory usage, but will result in slower writes.
+write-batch-size = 5000000
+
+# The server will check this often for shards that have expired that should be cleared.
 retention-sweep-period = "10m"
 
+[storage.engines.leveldb]
+
+# Maximum mmap open files, this will affect the virtual memory used by
+# the process
+max-open-files = 1000
+
+# LRU cache size, LRU is used by leveldb to store contents of the
+# uncompressed sstables. You can use `m` or `g` prefix for megabytes
+# and gigabytes, respectively.
+lru-cache-size = "200m"
+
+[storage.engines.rocksdb]
+
+# Maximum mmap open files, this will affect the virtual memory used by
+# the process
+max-open-files = 1000
+
+# LRU cache size, LRU is used by rocksdb to store contents of the
+# uncompressed sstables. You can use `m` or `g` prefix for megabytes
+# and gigabytes, respectively.
+lru-cache-size = "200m"
+
+[storage.engines.hyperleveldb]
+
+# Maximum mmap open files, this will affect the virtual memory used by
+# the process
+max-open-files = 1000
+
+# LRU cache size, LRU is used by rocksdb to store contents of the
+# uncompressed sstables. You can use `m` or `g` prefix for megabytes
+# and gigabytes, respectively.
+lru-cache-size = "200m"
+
+[storage.engines.lmdb]
+
+map-size = "100g"
+
 [cluster]
 # A comma separated list of servers to seed
 # this server. this is only relevant when the
@@ -69,7 +153,7 @@
 # as a seed. It will find the Raft leader automatically.
 
 # Here's an example. Note that the port on the host is the same as the raft port.
-seed-servers = ["hosta:8090", "hostb:8090"]
+# seed-servers = ["hosta:8090","hostb:8090"]
 
 # Replication happens over a TCP connection with a Protobuf protocol.
 # This port should be reachable between all servers in a cluster.
@@ -115,7 +199,7 @@
 
 [wal]
 
-dir   = "/tmp/influxdb/development/wal"
+dir   = "/var/db/influxdb/wal"
 # flush-after = 0 # the number of writes after which wal will be flushed, 0 for flushing on every write
 # bookmark-after = 0 # the number of writes after which a bookmark will be created
 
